my: 
 greeting: HelloWorld

app:
 name: My app
 description: Welcome to ${app.name}
 list:
  values: one,two,three
 db:
  values: "{connectionString: 'http://__________', userName: 'foo', password: 'foopass'}"
  
db: 
 connection: "{connectionString: 'http://__________', userName: 'foo', password: 'foopass'}"
 host: 127.0.0.1
 port: 1200
 
#enable actuator endpoints
management.endpoints.web.exposure.include: "*"