server:
  port : 8081

spring.cloud.stream:
  function:
    definition: evenNumberSquareProcessor # spring cloud function bean name
  bindings: # Using in we consume the data, then to write we use out
    evenNumberSquareProcessor-in-0:
      destination: numbers # Topic name
    evenNumberSquareProcessor-out-0:
      destination: squaredNumbers # Topic name
  kafka:
    binder:
      brokers:
        - localhost:9092
        - localhost:9093
        - localhost:9094