server:
  port : 8082

spring.cloud.stream:
  function:
    definition: squaredNumberConsumer # spring cloud function bean name
  bindings:
    squaredNumberConsumer-in-0: # To consume the data use in
      destination: squaredNumbers # topic name
  kafka:
    binder:
      brokers:
        - localhost:9092
        - localhost:9093
        - localhost:9094