server:
 port: 8080
 servlet:
  context-path: /cqrs-order-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cqrs-purchase-order
    username: postgres
    password: 1qaz2wsx@

app:
  write:
    enabled: true
