server:
 port: 8081
 servlet:
  context-path: /es-order-service

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: es-purchase-order
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    consumer:
      group-id: es-user-service-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.LongDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

